import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import cst8117Sidebar from './sidebars/cst8117'
import cst8279Sidebar from './sidebars/cst8279'
import cst8209Sidebar from './sidebars/cst8209';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  cst8117Sidebar,
  cst8279Sidebar,
  cst8209Sidebar,
  cst8260Sidebar: ['cst8260/index'],
  cst8250Sidebar: ['cst8250/index'],
  cst8253Sidebar: ['cst8253/index'],
  cst8254Sidebar: ['cst8254/index'],
  cst8318Sidebar: ['cst8318/index'],
  cst8256Sidebar: ['cst8256/index'],
  cst8257Sidebar: ['cst8257/index'],
  cst8259Sidebar: ['cst8259/index'],
  cst8265Sidebar: ['cst8265/index'],
};

export default sidebars;
